### ISSUE TITLE
Cannot connect to standalone hawkular-metrics

### ISSUE THREAD

**Issue by Fryguy** [pilhuhn/hawkfx#14]
I am using the standalone hawkular-metrics provided as a homebrew package here: https://github.com/hawkular/homebrew-hawkular .  Unfortunately, HawkFX can't connect.  I *think* it's trying to access `http://localhost:8080/hawkular/inventory/status`, but since inventory doesn't exist in the standalone package, it returns a 404.

Note that the error I get in the little box is

```
Error: <html><head><title>Error</title></head><body>404 - Not Found</body></html>
```

It might be a helpful feature to show what URL it's trying to connect to when there's an error.  The reason I'm guessing it's trying to hit inventory/status above is because I changed the server URL to `http://localhost:8080/hawkular/metrics` and instead the different error I got is

```
Error: RESTEASY003210: Could not find resource for full path: http://localhost:8080/hawkular/metrics/hawkular/inventory/status
```

**Comment by pilhuhn** [comment]
The problem is the way I changed obtaining the client, which is not valid for Hawkular-metrics usage. Will change this.
