### ISSUE TITLE
Unable to start hawkfx: uninitialized constant ValueElement::Logging

### ISSUE THREAD

**Issue by Jiri-Kremser** [pilhuhn/hawkfx#33]
Exception running Application:
#<NameError: uninitialized constant ValueElement::Logging

perhaps the require is missing somewhere in the code? (http://stackoverflow.com/a/24531676/1594980)

http://pastebin.com/gZ53En7n

**Comment by pilhuhn** [comment]
On 18 Jan 2017, at 16:21, Jirka Kremser wrote:

> Exception running Application:
> #<NameError: uninitialized constant ValueElement::Logging
>
> perhaps the require is missing somewhere in the code? 
> (http://stackoverflow.com/a/24531676/1594980)
>
> http://pastebin.com/gZ53En7n

TomC had a similar issue lately and he solved it by upgrading
to a new(er) Java version (he was on 8u31 or so).
Also note that JRuby 9.1.6/.7 is broken - you have to use
JRuby 9.1.5

**Comment by Jiri-Kremser** [comment]
that was it. just fyi the hotspot @ 8u45 didn't work either
