### ISSUE TITLE
buttons are not big enough to fix the labels

### ISSUE THREAD

**Issue by jmazzitelli** [pilhuhn/hawkfx#9]
![hawkfx-button-labels](https://cloud.githubusercontent.com/assets/2029470/16693307/a8f52260-4502-11e6-82e3-754cb1abcd3c.png)

**Comment by pilhuhn** [comment]
@jmazzitelli Does that look better now?

**Comment by jmazzitelli** [comment]
yes.

**Comment by pilhuhn** [comment]
This was changed in b2378c14a1
